variables:
- name: ReleaseEnvironmentName
  value: sit
- name: ResourceGroup
  value: dfc-sit-stax-editor-rg
- name: WebAppName
  value: dfc-sit-stax-editor-as
- name: SqlDatabaseName
  value: dfc-sit-stax-editor-db
- name: OrchardCoreSqlDatabaseConnStr
  value: Server=tcp:$(sharedSqlServerName).database.windows.net,1433;Initial Catalog=$(SqlDatabaseName);Persist Security Info=False;User ID=$(WebAppName)-svc;Password=$(OrchardEditorSqlUserPassword);MultipleActiveResultSets=True;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
- name: FunctionalTestsSqlDatabaseConnStr
  value: 'Server=tcp:$(sharedSqlServerName).database.windows.net,1433;Initial Catalog=$(SqlDatabaseName);Persist Security Info=False;User ID=$(FunctionalTestsUser);Password=$(FunctionalTestsUserPassword);MultipleActiveResultSets=True;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'
- name: EventGridEnabled
  value: true
- name: EventGridTopicSku
  value: basic
- name: Neo4jEndpoints0Enabled
  value: true
- name: Neo4jEndpoints1Enabled
  value: false
- name: Neo4jEndpoints2Enabled
  value: true
- name: Neo4jEndpoints3Enabled
  value: false
- name: Neo4jReplicaSets0GraphInstances0Enabled
  value: true
- name: Neo4jReplicaSets0GraphInstances1Enabled
  value: false
- name: Neo4jReplicaSets1GraphInstances0Enabled
  value: true
- name: Neo4jReplicaSets1GraphInstances1Enabled
  value: false